### ISSUE TITLE
[質問] 8章 WAIT = 0.005（5ミリ秒）の理由

### ISSUE THREAD

**Issue by ToshiShibuya** [matsujirushi/raspi_parts_kouryaku#1]
**章**  
８章

**ページ番号**  
p128～140
「drv8835.py」,「drv8835-2.py」,「a4988.py」内で設定しているコイルに電流を流す時間（5ミリ秒）：WAIT = 0.005 について

**内容**  
ステッピングモータ駆動プログラム内にあるコイルに電流を流す時間（5ミリ秒）：WAIT = 0.005 について
教えて頂けないでしょか。

秋月電子にあるステッピングモータの資料やドライバの取扱説明書を確認しましたが、
この設定時間についての項目を見つける事が出来ず、
この値を設定した理由を教えて頂けないでしょうか？

申し訳ありませんが
どうぞ宜しくお願い致します。

**Comment by matsujirushi** [comment]
ご質問ありがとうございます。

「WAIT = 0.005」にした理由ですが、ご認識のとおり紙面には書いていませんでした。
データシートから算出するような深い意味合いは無く、執筆時はdrv8835.pyで「1回転1秒くらいで動かそう」と決めて、1秒/200ステップ=5ミリ秒としました。以降のプログラムでは、同じ値をそのまま使っただけです。

ミスリードしてしまい、余分な調査をさせてしまったようで申し訳ないです。
またなにか疑問な部分があれば、お気軽にご連絡くださいませ。
